### PR TITLE
Fix undo/redo not working for cut range

### PR DESCRIPTION
**Pull request by ottosson**
I took a stab at #236. I've implemented the fix quite naively and just want to start the discussion around this fix. Maybe it's good enough already, maybe not.

### CODE REVIEW

**Review by jingwood — APPROVED** [review]
Hi! Thanks for the pull request! I'm going to merge it.

How about if we provide an option to indicate whether or not to use action to perform Cut? Or maybe we could provide two methods like 'Cut' and 'CutByAction'.

**Comment by ottosson** [comment]
I guess it could be useful to separate programmatic cut and user actions? Or how are you thinking about it? I'm not arguing against it I just want to understand so I can implement it correctly.

**Comment by jingwood** [comment]
Hi @ottosson!

Thanks for your PR. I appreciate it.

I have implemented the idea, could you please have a review on this PR? Thanks!
https://github.com/unvell/ReoGrid/pull/452

**Comment by ottosson** [comment]
Excellent! Thanks a lot! 👍

**Pull request merged**
