### PR TITLE
Refactored autofill serial to remove duplication and exclude autofilling to readonly cells

### PR DESCRIPTION
**Pull request by Xcone**
Hi, 

I encountered an issue when autofill would overlap readonly cells, and just wanted to quickly fix it. Then I learned of some duplication in this bit of code, and quite  huge, hard to comprehend method. So I refactored that first. These commits are the result.

After testing I discovered a small functional change as well that had snuck in. When autofilling on merged cells it used to increment with the amount of merged cells, instead of treating them as one cell. I realised it actually makes more sense to me to count a merged cell as one cell, so I delibirately did not fix it.

Summary:
- Cleaner code for AutoFill
- AutoFill over merged cells counts better
- AutoFill over readonly cells will not fill the content of the cell.

I hope you like it. :-)

### CODE REVIEW

**Comment by Xcone** [comment]
Abort the AutoFill operation by throwing exception, similar to Jingwoods change in #33

**Comment by jingwood** [comment]
Hi Xcone, thanks for the pull request and changes.

I just found a problem that exception happens when filling a serial that contains merged cell on every rows when using this pull request. I will check it and try to fix it. If you have any ideas about this please let me know.

**Comment by Xcone** [comment]
Hi, I'm trying to reproduce it, but I have little info to go on. I tried some combinations of merged cells and apply fill serial, but I don't get any exception. Could you provide steps and/or a file with a range setup that can help me to reproduce it?

**Comment by jingwood** [comment]
@Xcone, sorry for less details. Please try run this code:

```csharp
sheet.MergeRange("B3:D4");
sheet.MergeRange("B5:D6");
sheet["B3"] = 1;
sheet["B5"] = 2;
sheet.AutoFillSerial("B3:D6", "B7:D11");
```

**Comment by Xcone** [comment]
Thanks. Found the exception now (it was hidden by UI before). And I fixed it as well. 

P.S. Any indication when you'll repost the NuGet package containing these changes? Assuming it's all fixed now, of course ;-)

**Comment by jingwood** [comment]
Thanks @Xcone, now it works greatly. I will public a NuGet package containing these changes.

**Pull request merged**
