### PR TITLE
fix(ExcelReader): Reading the Excel 2007 format when CurrentCulture is not English Culture

### PR DESCRIPTION
**Pull request by workgroupengineering**

### CODE REVIEW

**Comment by abstractspoon** [comment]
Hi workgroupengineering

I'm really interested in your work here but am still having problems with currency values.

Under the French (France) locale, saving '75,90 €' to a cell always gets converted to '75,900000' when I reload the document.

Does this issue also arise for you?

**Comment by workgroupengineering** [comment]
Hi,
have you tried with this pr? should solve the issue.

**Comment by abstractspoon** [comment]
I'll download and build your entire repo to see if that improves things...

[Update] Problem is still there.

**Comment by workgroupengineering** [comment]
Can you attach a simple excel file with the issue?

**Comment by abstractspoon** [comment]
Here you go:

[Example_Files.zip](https://github.com/unvell/ReoGrid/files/8692514/Example_Files.zip)

**Comment by jingwood** [comment]
@workgroupengineering Hi! Thanks for the pull request! and sorry for late merging.

**Pull request merged**
