### PR TITLE
Improve the width of column and make it look better.

### PR DESCRIPTION
**Pull request by a188037445**

### CODE REVIEW

**Comment by jingwood** [comment]
Thanks! Can you add some description or pictures to explain this PR?

**Comment by jingwood** [comment]
@a188037445 Thanks! Can you add some description or pictures to explain this PR?

**Comment by a188037445** [comment]
before:
)D8OM}0880I$RP_4%INWQ_A
after:
A0P8FXL}LT8IZ95O`QSOL9X
I made columns 10 sizes wider than it needed to be and added a minimum of 30 sizes to the width of columns.

**Comment by jingwood** [comment]
@a188037445 Thanks a lot for this pull request, but sorry I can't merge this because the minimum width of column is according to the application business, we shouldn't decide it on component side.

If you have other changes else, please feel free to share it, thanks!

**Pull request closed without merging**
